name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: bun install --no-save

      - name: Build
        run: bun run build

      - name: Publish Packages
        run: |
          package_name=$(node -p "require('./package.json').name")
          current_latest=$(node -p "require('./package.json').version")
          IFS='.' read -r major minor patch <<< "$current_latest"
          future_latest="$major.$((minor + 1)).0"
          current_canary=$(npm view "$package_name" dist-tags.canary --real 2>/dev/null)
          if [ -z "$current_canary" ]; then
          future_canary="$future_latest-canary.0"
          else
          IFS='.-' read -r canary_major canary_minor canary_patch canary_tag canary_version <<< "$current_canary"
          future_canary="$canary_major.$canary_minor.$canary_patch-canary.$((canary_version + 1))"
          fi
          echo "$current_latest"
          echo "$future_latest"
          echo "$current_canary"
          echo "$future_canary"
          bunx json -I -f package.json -e "this.version=\"$future_canary\""
          npm publish --access public --tag canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
