name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish Packages
        run: |
          package_name=$(bunx json -f package.json -a name)
          if ! npm view "$package_name" > /dev/null 2>&1; then
            echo "Package does not exist. Publishing the package for the first time."
            bun publish --provenance --access public
            exit 0
          fi
          current_version=$(bunx json -f package.json -a version)
          IFS='.' read -r major minor patch <<< "$current_version"
          future_latest="$major.$((minor + 1)).0"
          current_canary=$(npm view "$package_name" dist-tags.canary 2>/dev/null)
          if [ -z "$current_canary" ]; then
          future_canary="$future_latest-canary.0"
          else
          IFS='.-' read -r canary_major canary_minor canary_patch canary_tag canary_version <<< "$current_canary"
          future_canary="$canary_major.$canary_minor.$canary_patch-canary.$((canary_version + 1))"
          fi
          bunx json -I -f package.json -e "this.version=\"$future_canary\""
          bun publish --provenance --access public --tag canary
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
